[build-system]
requires = ["setuptools>=68", "wheel", "poetry-core"]
build-backend = "poetry.core.masonry.api"


[project]
name = "parallax"
version = "0.0.1"
description = "Decentralised pipeline-parallel LLM serving with MLX-LM + Hivemind"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "mlx-lm @ git+https://github.com/ml-explore/mlx-lm.git",
  "msgpack>=1.0.7",
  "safetensors>=0.5.1",
  "numpy>=1.26",
  "pyzmq>=25.0",
  "psutil>=5.9.5",
  "httpx",
  "protobuf==6.31.1",
  "hivemind @ git+https://github.com/learning-at-home/hivemind.git@53533289edfeb1f9b2f5917cbae66fe50cfa2548",
  "dijkstar",
  "uvicorn",
  "uvloop",
  "fastapi",
  "pydantic",
]

[project.optional-dependencies]
dev = [
  "black>=24.3",
  "ruff>=0.4",
  "pytest>=8.2",
  "pytest-mock>=3.14",
  "pytest-cov>=5.0",
  "pre-commit>=3.2",
  "pylint>=3.2",
]

[tool.setuptools.packages.find]
where = ["src"]                # put your code under ./src/…

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.ruff]
ignore = ["E501"]              # line length handled by Black
line-length = 100

[tool.pylint.main]
ignore-patterns = "p2p/.*"
