[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "dllm"
version = "0.0.1"
description = "Decentralised pipeline-parallel LLM serving with MLX-LM + Hivemind"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "mlx-lm>=0.0.4",
  "hivemind[p2p]>=1.1.11",
  "protobuf>=4.25.0",
  "msgpack>=1.0.7",
  "safetensors>=0.5.1",
  "numpy>=1.26",
]

[project.optional-dependencies]
dev = [
  "black>=24.3",
  "ruff>=0.4",
  "pytest>=8.2",
  "pre-commit>=3.2",
  "pylint>=3.2",
]

[tool.setuptools.packages.find]
where = ["src"]                # put your code under ./src/dllm/…

[tool.black]
line-length = 100

[tool.ruff]
ignore = ["E501"]              # line length handled by Black
