[build-system]
requires = ["setuptools>=68", "wheel", "poetry-core"]
build-backend = "poetry.core.masonry.api"


[project]
name = "parallax"
version = "0.0.1"
description = "Decentralised pipeline-parallel LLM serving with MLX-LM + Hivemind"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "mlx-lm==0.26.4",
  "mlx==0.28.0",
  "torch==2.8.0",
  "sglang[runtime_common]==0.5.1.post3",
  "msgpack>=1.0.7",
  "safetensors>=0.5.1",
  "numpy>=1.26",
  "pyzmq>=25.0",
  "psutil>=5.9.5",
  "httpx",
  "protobuf==6.31.1",
  "dijkstar==2.6.0",
  "uvicorn",
  "uvloop",
  "fastapi",
  "pydantic",
  "lattica @ git+https://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@github.com/OpenEdgeHQ/p2p-lattica.git#subdirectory=bindings/python",
]

[project.optional-dependencies]
dev = [
  "black>=24.3",
  "ruff>=0.4",
  "pytest>=8.2",
  "pytest-mock>=3.14",
  "pytest-cov>=5.0",
  "pre-commit>=3.2",
  "pylint>=3.2",
]

[tool.setuptools.packages.find]
where = ["src"]                # put your code under ./src/…

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.ruff]
ignore = ["E501"]              # line length handled by Black
line-length = 100

[tool.pylint.main]
ignore-patterns = "p2p/.*"
