FROM lmsysorg/sglang:spark

ENV SGLANG_ENABLE_JIT_DEEPGEMM=0

WORKDIR /parallax

COPY README.md ./README.md
COPY src ./src
COPY pyproject.toml ./pyproject.toml

RUN apt-get update

RUN git clone --barnch v0.29.1 https://github.com/ml-explore/mlx.git && \
    apt-get install libblas-dev liblapack-dev liblapacke-dev -y && \
    cd mlx && \
    PYPI_RELEASE=1 pip install . && \
    cd ..

RUN pip install -e '.[gpu]'
